version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rdok-local-aws-sam-laravel"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gls3cd4hrabc"
s3_prefix = "rdok-local-aws-sam-laravel"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"aws-sam-laravel-local.rdok.co.uk\""

[certificate]
[certificate.deploy]
[certificate.deploy.parameters]
stack_name = "rdok-local-aws-sam-laravel-certificate"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tsljwszxn1ow"
s3_prefix = "rdok-local-aws-sam-laravel-certificate"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"aws-sam-laravel-local.rdok.co.uk\" Route53HostedZoneId=\"ZSY7GT2NEDPN0\""

[database]
[database.deploy]
[database.deploy.parameters]
stack_name = "rdok-local-aws-sam-laravel-database"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gls3cd4hrabc"
s3_prefix = "rdok-local-aws-sam-laravel-database"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
