name: Check

on:
  pull_request:
    branches: [ main ]
  workflow_call:
  workflow_dispatch:

jobs:

  test:
    name: Run Feature & Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download docker layers caches
        uses: "satackey/action-docker-layer-caching@v0.0.11"
        continue-on-error: true
      - name: Download Composer caches
        uses: actions/cache@v3
        with:
          path: laravel/.composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer packages
        run: make ci-install-composer-packages
      - name: Build Laravel
        run: make ci-build-laravel
      - name: Start Laravel
        run: make ci-start-laravel-sail
      - name: Download NPM caches
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install NPM packages
        run: make ci-install-npm
      - name: Compile JS & CSS
        run: make ci-compile-js-css
      - name: Setup .env
        run: make ci-setup-env
      - name: Run Laravel Tests
        run: make ci-test
